version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acms_dashboard_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=acms_dashboard
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: acms_dashboard_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: acms_dashboard
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
